
// This file has been generated by the GUI designer. Do not modify.

public partial class Exception
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Label Exe;
	
	private global::Gtk.Image image1;
	
	private global::Gtk.Button buttonCancel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget Exception
		this.Name = "Exception";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Internal child Exception.VBox
		global::Gtk.VBox w1 = this.VBox;
		w1.Name = "dialog1_VBox";
		w1.BorderWidth = ((uint)(2));
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Exe = new global::Gtk.Label ();
		this.Exe.WidthRequest = 400;
		this.Exe.HeightRequest = 50;
		this.Exe.Name = "Exe";
		this.Exe.LabelProp = global::Mono.Unix.Catalog.GetString ("Сообщение");
		this.Exe.Wrap = true;
		this.fixed1.Add (this.Exe);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Exe]));
		w2.X = 17;
		w2.Y = 5;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.image1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, ".\\icons\\NO.png"));
		this.fixed1.Add (this.image1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image1]));
		w3.X = 109;
		w3.Y = 61;
		w1.Add (this.fixed1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed1]));
		w4.Position = 0;
		// Internal child Exception.ActionArea
		global::Gtk.HButtonBox w5 = this.ActionArea;
		w5.Name = "dialog1_ActionArea";
		w5.Spacing = 10;
		w5.BorderWidth = ((uint)(5));
		w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonCancel = new global::Gtk.Button ();
		this.buttonCancel.CanDefault = true;
		this.buttonCancel.CanFocus = true;
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.UseStock = true;
		this.buttonCancel.UseUnderline = true;
		this.buttonCancel.Label = "gtk-ok";
		this.AddActionWidget (this.buttonCancel, -5);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonCancel]));
		w6.Expand = false;
		w6.Fill = false;
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 428;
		this.DefaultHeight = 401;
		this.Show ();
	}
}
