
// This file has been generated by the GUI designer. Do not modify.
namespace Lab5
{
	public partial class CircleSettings
	{
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Entry Radius;
		
		private global::Gtk.Label Label;
		
		private global::Gtk.CheckButton Square;
		
		private global::Gtk.CheckButton Length;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Lab5.CircleSettings
			this.Name = "Lab5.CircleSettings";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DestroyWithParent = true;
			// Internal child Lab5.CircleSettings.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.Radius = new global::Gtk.Entry ();
			this.Radius.WidthRequest = 300;
			this.Radius.CanFocus = true;
			this.Radius.Name = "Radius";
			this.Radius.IsEditable = true;
			this.Radius.InvisibleChar = '●';
			this.fixed2.Add (this.Radius);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.Radius]));
			w2.X = 65;
			w2.Y = 3;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.Label = new global::Gtk.Label ();
			this.Label.Name = "Label";
			this.Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Радиус");
			this.fixed2.Add (this.Label);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.Label]));
			w3.X = 13;
			w3.Y = 6;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.Square = new global::Gtk.CheckButton ();
			this.Square.CanFocus = true;
			this.Square.Name = "Square";
			this.Square.Label = global::Mono.Unix.Catalog.GetString ("Площадь");
			this.Square.DrawIndicator = true;
			this.Square.UseUnderline = true;
			this.fixed2.Add (this.Square);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.Square]));
			w4.X = 13;
			w4.Y = 41;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.Length = new global::Gtk.CheckButton ();
			this.Length.CanFocus = true;
			this.Length.Name = "Length";
			this.Length.Label = global::Mono.Unix.Catalog.GetString ("Длина");
			this.Length.DrawIndicator = true;
			this.Length.UseUnderline = true;
			this.fixed2.Add (this.Length);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.Length]));
			w5.X = 115;
			w5.Y = 41;
			w1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed2]));
			w6.Position = 0;
			// Internal child Lab5.CircleSettings.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonOk]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 388;
			this.DefaultHeight = 146;
			this.Show ();
			this.buttonOk.Pressed += new global::System.EventHandler (this.OnButtonOkPressed);
		}
	}
}
