
// This file has been generated by the GUI designer. Do not modify.
namespace Lab5
{
	public partial class Calc
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label SquareLabel;
		
		private global::Gtk.Label LengthLabel;
		
		private global::Gtk.Label Square;
		
		private global::Gtk.Label Length;
		
		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Lab5.Calc
			this.Name = "Lab5.Calc";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Lab5.Calc.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.SquareLabel = new global::Gtk.Label ();
			this.SquareLabel.Name = "SquareLabel";
			this.SquareLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Площадь =");
			this.fixed1.Add (this.SquareLabel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SquareLabel]));
			w2.X = 7;
			w2.Y = 6;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.LengthLabel = new global::Gtk.Label ();
			this.LengthLabel.Name = "LengthLabel";
			this.LengthLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Длина =");
			this.fixed1.Add (this.LengthLabel);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.LengthLabel]));
			w3.X = 25;
			w3.Y = 24;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.Square = new global::Gtk.Label ();
			this.Square.Name = "Square";
			this.Square.LabelProp = global::Mono.Unix.Catalog.GetString ("123");
			this.fixed1.Add (this.Square);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Square]));
			w4.X = 74;
			w4.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.Length = new global::Gtk.Label ();
			this.Length.Name = "Length";
			this.Length.LabelProp = global::Mono.Unix.Catalog.GetString ("123");
			this.fixed1.Add (this.Length);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Length]));
			w5.X = 74;
			w5.Y = 25;
			w1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed1]));
			w6.Position = 0;
			// Internal child Lab5.Calc.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-ok";
			this.AddActionWidget (this.buttonCancel, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 222;
			this.DefaultHeight = 133;
			this.Square.Hide ();
			this.Length.Hide ();
			this.Show ();
		}
	}
}
