
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action InputAction;
	
	private global::Gtk.Action CalcAction;
	
	private global::Gtk.Action DrawAction;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.DrawingArea Area;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.InputAction = new global::Gtk.Action ("InputAction", global::Mono.Unix.Catalog.GetString ("Input"), null, null);
		this.InputAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Input");
		w1.Add (this.InputAction, null);
		this.CalcAction = new global::Gtk.Action ("CalcAction", global::Mono.Unix.Catalog.GetString ("Calc"), null, null);
		this.CalcAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Calc");
		w1.Add (this.CalcAction, null);
		this.DrawAction = new global::Gtk.Action ("DrawAction", global::Mono.Unix.Catalog.GetString ("Draw"), null, null);
		this.DrawAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Draw");
		w1.Add (this.DrawAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'InputAction\' action=\'InputAction\'/><menu" +
		" name=\'CalcAction\' action=\'CalcAction\'/><menu name=\'DrawAction\' action=\'DrawActi" +
		"on\'/><menu name=\'ExitAction\' action=\'ExitAction\'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.WidthRequest = 550;
		this.menubar1.Name = "menubar1";
		this.fixed1.Add (this.menubar1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.menubar1]));
		w2.X = 13;
		w2.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Area = new global::Gtk.DrawingArea ();
		this.Area.WidthRequest = 600;
		this.Area.HeightRequest = 600;
		this.Area.Name = "Area";
		this.fixed1.Add (this.Area);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Area]));
		w3.X = 20;
		w3.Y = 40;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 652;
		this.DefaultHeight = 675;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.InputAction.Activated += new global::System.EventHandler (this.OnInputActionActivated);
		this.CalcAction.Activated += new global::System.EventHandler (this.OnCalcActionActivated);
		this.DrawAction.Activated += new global::System.EventHandler (this.OnDrawActionActivated);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnExitActionActivated);
	}
}
